apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: result
  template:
    metadata:
      labels:
        component: result
    spec:
      containers:
        - name: result
          image: busfahrer/simple-result:v6
          ports:
            - containerPort: 80
